export { partial } from './partialApplication';
export { curry } from './currying';
export { fold } from './linearFold';
export { unfold } from './linearUnfold';
export { map } from './map';
export { filter } from './filter';
export { firstElement } from './firstElement';
export { lazy } from "./lazy";
export { memoize } from './memoize';
